### ISSUE TITLE
Strange landing page for Windows console's "Learn more about legacy console mode" link

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/Console-Docs#112] opened 2019-11-20 13:24 UTC
When you click that link in the Windows console's (i.e. CMD/PowerShell 5.1) options, you end up on this basically empty page.

PS, I've noticed that some of the same quirks from Windows Terminal (Preview) now plague the Windows console.  An example is copying PowerShell code into or out of the console - no longer works well, and it includes previously-nonexistent trailing whitespace when copying out of the console (boo...).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ada9ec05-3269-9fb2-bd0b-b01bfafd86a7
* Version Independent ID: 3a38151f-1a94-fc14-29a1-d2b16bce6926
* Content: [Console documentation - Windows Console](https://docs.microsoft.com/en-us/windows/console/)
* Content Source: [docs/index.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/index.md)
* Product: **console**
* GitHub Login: @bitcrazed
* Microsoft Alias: **richturn**

**Comment by zadjii-msft** [comment] 2019-11-20 13:52
Hey wadda ya know, this is actually something we've been bothering @bitcrazed to update for a while now 😝 

For any problems you might be having with the Windows Terminal, I'd recommend searching for issues on https://github.com/microsoft/terminal and filing a new issue if you don't find a duplicate.

**Comment by JeremyTBradshaw** [comment] 2019-11-20 17:31
Duly noted @zadjii-msft re: terminal issues.  Thanks!

**Comment by bitcrazed** [comment] 2019-11-20 18:54
Assigning to @cinnamon_msft since she's now the owner of all our AKA.MS and FWLINK URLs.

**Comment by jgmy** [comment] 2019-11-20 21:28
I arrived here the same way JeremyTBradshaw did. And I don't find any information about legacy console in the index.

**Comment by fde-capu** [comment] 2019-12-17 11:22
I have been stumbling at this (rather old empty) page ever once in a week; looking forward to understand the need to check/un-check it every time I switch between cmd.exe and Ubuntu WSL.

**Comment by DHowett-MSFT** [comment] 2019-12-19 23:41
@fde-capu We would _also_ love to understand your need to check it every time you switch between cmd.exe and WSL. The legacy console is intended only for compatibility with applications that don't work properly in the non-legacy console or require very specific console behaviors (like 16-bit applications tend to).

CMD is _not_ one of those applications.

What behaviors are you seeing that lead to you enabling the legacy console? What's happening?

**Comment by fde-capu** [comment] 2019-12-20 19:21
Unchecked: WSL works, CMD does not prompt (black screen).
Checked: CMD works, WSL flashes but does not open.
So if I want WSL and it bugs while opening, I go to CMD to uncheck legacy and vice versa.

**Comment by DHowett-MSFT** [comment] 2019-12-20 19:36
Oh! So, this is a little ironic. Turning on legacy console on Windows 1903 causes a visual issue with CMD that makes it turn black when you turn legacy mode back _off_.

The extended terminal colors get set to black of black with a black cursor.

You can resolve this by:

1. Making sure legacy mode is turned _off_
2. Visiting the "Terminal" settings
3. Making sure that "use separate foreground," "use separate background," and "cursor  > use color" are _not_ selected.

![image](https://user-images.githubusercontent.com/14316954/71287323-f4b85900-231c-11ea-9744-3274d78cb850.png)

![image](https://user-images.githubusercontent.com/14316954/71287347-0437a200-231d-11ea-8950-22e65ca9ad69.png)

**Comment by fde-capu** [comment] 2019-12-20 19:48
I can confirm. I could cut and paste the black-on-black content. In fact "Terminal" is auto blinding itself when going back from legacy. Foreground and Background were checked and set to black. Still, WSL will not work with legacy on, I guess this would be expected.

> The legacy console is intended only for compatibility with applications that don't work properly in the non-legacy console or require very specific console behaviors (like 16-bit applications tend to).
- This is much more clarifying than the landing page in question.

**Comment by jgmy** [comment] 2019-12-20 21:44
Yes, i had the same issue with WIndows Services for Linux and the console.
I installed and uninstalled WSL because I could not get a login window with
console extensions enabled, just before I noticed I could *copy* text.
Having *two* tabs where choose console color scheme is weird. And so is the
black over black scheme.

Well, I am colorblind and sometimes I had dreamed on publishing a book
printed using white ink over white paper as a response to all these people
who uses weird color schemes such as purple vs blue or red over black. But
the programmer who put black ink and black background as default scheme for
the console is definitely my idol.

**Comment by DHowett-MSFT** [comment] 2019-12-20 21:57
> ... is weird ... and so is the black over black scheme ... definitely my idol

Just to be clear, this isn't by design or by intent: that the colors get reset to black on black is simply an unfortunate bug.

**Comment by jgmy** [comment] 2019-12-20 22:08
Is the first time I hear someone at Microsoft say something is a bug, not a
feature.

Envío desde móvil y no veo bien la pantalla. Disculpe las erratas y faltas.

**Comment by zadjii-msft** [comment] 2019-12-20 22:11
@jgmy Well get excited then, because here's [50 other things I've said are bugs](https://github.com/microsoft/terminal/issues?q=is%3Aopen+is%3Aissue+author%3Azadjii-msft+label%3AIssue-Bug) in our own product, as well as about 800 more we're tracking :)

**Comment by Hentaya** [comment] 2020-01-09 04:39
Just confirming the OP, the link tries to go to https://go.microsoft.com/fwlink/?LinkId=871150 which ends up being https://docs.microsoft.com/en-us/windows/console/ instead of an explanation of what Legacy Console Mode is. Windows 10 Home 1903 build 18362.535

Home? EWWW. I have to fix that. :)

**Closed** 2020-02-13 21:10 UTC
Labels: Redirect, Size-Large
